/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'materials' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const ShippingDetails = IDL.Record({
  'contact' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'total' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'createdAt' : IDL.Int,
  'shipping' : ShippingDetails,
  'items' : IDL.Vec(OrderItem),
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'tagline' : IDL.Text,
  'logoUrl' : IDL.Text,
  'storeName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getNewsletterSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUpiId' : IDL.Func([], [IDL.Text], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([Order], [IDL.Nat], []),
  'setAdmin' : IDL.Func([IDL.Principal], [], []),
  'setSiteSettings' : IDL.Func([SiteSettings], [], []),
  'setUpiId' : IDL.Func([IDL.Text], [], []),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [IDL.Bool], []),
  'whoami' : IDL.Func([], [IDL.Principal], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'materials' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ShippingDetails = IDL.Record({
    'contact' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
  });
  const OrderItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'total' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'createdAt' : IDL.Int,
    'shipping' : ShippingDetails,
    'items' : IDL.Vec(OrderItem),
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const SiteSettings = IDL.Record({
    'tagline' : IDL.Text,
    'logoUrl' : IDL.Text,
    'storeName' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getNewsletterSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUpiId' : IDL.Func([], [IDL.Text], ['query']),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([Order], [IDL.Nat], []),
    'setAdmin' : IDL.Func([IDL.Principal], [], []),
    'setSiteSettings' : IDL.Func([SiteSettings], [], []),
    'setUpiId' : IDL.Func([IDL.Text], [], []),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [IDL.Bool], []),
    'whoami' : IDL.Func([], [IDL.Principal], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };