/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'total' : bigint,
  'paymentMethod' : string,
  'createdAt' : bigint,
  'shipping' : ShippingDetails,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'productId' : bigint, 'quantity' : bigint }
export interface Product {
  'id' : bigint,
  'featured' : boolean,
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'stock' : bigint,
  'materials' : string,
  'category' : string,
  'price' : bigint,
}
export interface ShippingDetails {
  'contact' : string,
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'name' : string,
  'state' : string,
  'address' : string,
}
export interface SiteSettings {
  'tagline' : string,
  'logoUrl' : string,
  'storeName' : string,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], bigint>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getNewsletterSubscribers' : ActorMethod<[], Array<string>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUpiId' : ActorMethod<[], string>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'placeOrder' : ActorMethod<[Order], bigint>,
  'setAdmin' : ActorMethod<[Principal], undefined>,
  'setSiteSettings' : ActorMethod<[SiteSettings], undefined>,
  'setUpiId' : ActorMethod<[string], undefined>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], boolean>,
  'updateProduct' : ActorMethod<[bigint, Product], boolean>,
  'whoami' : ActorMethod<[], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];